feat(publicK8S): add an ARM cluster node pool
jenkins-infra/azure pull request #369
Opened 2023-05-29 08:21 UTC by smerle33

as per https://github.com/jenkins-infra/helpdesk/issues/3584
create an ARM pool based on [Standard_D8ps_v5](https://learn.microsoft.com/en-us/azure/virtual-machines/dv5-dsv5-series#dsv5-series)

2023-05-29 08:48 UTC, smerle33 commented
Looks good, but need to make sure about the `os_disk_size_gb` as there is no temp storage on D8ps_v5 https://learn.microsoft.com/en-us/azure/virtual-machines/dpsv5-dpdsv5-series but a OS disk of 1023 GiB seems present : https://azureprice.net/vm/Standard_D8ps_v5

```
Terraform will perform the following actions:

  # azurerm_kubernetes_cluster_node_pool.publicarmpool will be created
  + resource "azurerm_kubernetes_cluster_node_pool" "publicarmpool" {
      + enable_auto_scaling   = true
      + id                    = (known after apply)
      + kubelet_disk_type     = (known after apply)
      + kubernetes_cluster_id = "..."
      + max_count             = 10
      + max_pods              = (known after apply)
      + min_count             = 0
      + mode                  = "User"
      + name                  = "pubarmpool"
      + node_count            = (known after apply)
      + node_labels           = (known after apply)
      + orchestrator_version  = (known after apply)
      + os_disk_size_gb       = (known after apply)
      + os_disk_type          = "Ephemeral"
      + os_sku                = (known after apply)
      + os_type               = "Linux"
      + priority              = "Regular"
      + scale_down_mode       = "Delete"
      + spot_max_price        = -1
      + tags                  = {
          + "repository" = "jenkins-infra/azure"
          + "scope"      = "terraform-managed"
        }
      + ultra_ssd_enabled     = false
      + vm_size               = "Standard_D8ps_v5"
      + vnet_subnet_id        = "..."
      + zones                 = [
          + "3",
        ]
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

2023-05-30 09:19 UTC, dduportal commented on publick8s.tf
> +  os_disk_size_gb       = 200 # Ref. Cache storage size at https://learn.microsoft.com/en-us/azure/virtual-machines/dv5-dsv5-series#dsv5-series (depends on the instance size)
```suggestion
  os_disk_size_gb       = 200 # Ref. Cache storage size at https://learn.microsoft.com/en-us/azure/virtual-machines/dpsv5-dpdsv5-series#dpdsv5-series (depends on the instance size)
```

2023-05-30 09:47 UTC, smerle33 commented
size needed for JAVADOC :

2023-05-30 14:18 UTC, dduportal submitted a review, later dismissed
YOu can set it ready for review and merge whenever you are ready!

2023-05-31 07:33 UTC, dduportal requested changes
Can you explain why we decided to add the new x86 medium (and explain the next step) please?

2023-05-31 07:33 UTC, dduportal commented on publick8s.tf
> +resource "azurerm_kubernetes_cluster_node_pool" "x86medimum" {
```suggestion
resource "azurerm_kubernetes_cluster_node_pool" "x86medium" {
```

2023-05-31 07:33 UTC, dduportal commented on publick8s.tf
> +  name                  = "x86medimum"
```suggestion
  name                  = "x86medium"
```

2023-05-31 08:32 UTC, smerle33 commented
> Can you explain why we decided to add the new x86 medium (and explain the next step) please?

as this PR create a dedicated ARM pool with a medium size machine, we decided to homogenize the other pool name (publicpool) in order to be able to provide others kind of node pools in the future (big for example).

2023-05-31 09:13 UTC, smerle33 commented
here is the steps we choose : 

- micro 2cpu/8G
- small 4cpu/16G
- medium 8cpu/32G
- big 16cpu/64G

2023-05-31 09:38 UTC, dduportal approved these changes
`Plan: 2 to add, 0 to change, 0 to destroy.` 

LGTM

2023-05-31 09:38 UTC, merged