feat(updates.jenkins.io): NS records for CloudFlare zones
jenkins-infra/azure pull request #486
Opened 2023-09-26 15:18 UTC by lemeurherve

This PR allows the creation of NS records corresponding to each CloudFlare zone created for updates.jenkins.io so they can be delegated to CloudFlare.

Follow-up of https://github.com/jenkins-infra/cloudflare/pull/13

Ref: https://github.com/jenkins-infra/helpdesk/issues/2649

2023-09-26 15:27 UTC, lemeurherve commented
LGTM:
```
Terraform will perform the following actions:

  # azurerm_dns_ns_record.updates_jenkins_io_cloudflare_zones["westeurope"] will be created
  + resource "azurerm_dns_ns_record" "updates_jenkins_io_cloudflare_zones" {
      + fqdn                = (known after apply)
      + id                  = (known after apply)
      + name                = "westeurope.cloudflare"
      + records             = [
          + "cody.ns.cloudflare.com",
          + "kallie.ns.cloudflare.com",
        ]
      + resource_group_name = "proddns_jenkinsio"
      + tags                = {
          + "repository" = "jenkins-infra/azure"
          + "scope"      = "terraform-managed"
        }
      + ttl                 = 60
      + zone_name           = "jenkins.io"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

2023-09-26 15:30 UTC, dduportal requested changes
No need to define in locals.tf as the value is not reused

2023-09-26 15:30 UTC, dduportal commented on updates.jenkins.io.tf
> +}
```suggestion
resource "azurerm_dns_ns_record" "updates_jenkins_io_cloudflare_zones" {
  name                = "${each.key}.cloudflare"
  zone_name           = data.azurerm_dns_zone.jenkinsio.name
  resource_group_name = data.azurerm_resource_group.proddns_jenkinsio.name
  ttl                 = 60
  # The record values should correspond to the "zones_name_servers" output defined in https://github.com/jenkins-infra/cloudflare/blob/main/updates.jenkins.io.tf
  records             = ["cody.ns.cloudflare.com", "kallie.ns.cloudflare.com"]
  tags                = local.default_tags
}
```

2023-09-26 15:30 UTC, dduportal commented on locals.tf
> +  }
```suggestion
```

2023-09-26 16:03 UTC, dduportal approved these changes

2023-09-26 16:07 UTC, lemeurherve commented
> Plan: 1 to add, 0 to change, 0 to destroy.

2023-09-26 16:07 UTC, merged

2023-09-27 13:50 UTC, lemeurherve commented
<img width="957" alt="image" src="https://github.com/jenkins-infra/azure/assets/91831478/9765fc55-c485-4047-92e8-8fed6cf28b21">